filegroup(
    name = "model",
    srcs = [
        "model.onnx",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "vocab",
    hdrs = ["vocab.h.inc"],
     visibility = ["//visibility:public"],
)
