# Packages for examples/debian_snapshot.
#
#  Anytime this file is changed, the lockfile needs to be regenerated.
#
#  To generate the bookworm.lock.json run the following command
#
#     bazel run @bookworm//:lock
#
# See debian_package_index at WORKSPACE.bazel
version: 1
sources:
  - channel: bookworm main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240210T223313Z
  - channel: bookworm-security main
    url: https://snapshot-cloudflare.debian.org/archive/debian-security/20240210T223313Z
  - channel: bookworm-updates main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240210T223313Z/
archs:
  - "amd64"
  - "arm64"
packages:
  - "bash"
  - "coreutils" # for commands like `ls`
  # for apt list --installed
  # test cacerts() compatibility
  - "ca-certificates"
  # xvfb
  - "xvfb"
  - "fluxbox"
  - "x11-apps"
  - "pulseaudio"
  # end xvfb
  - "chromium-driver"
  - "sudo"
  - "python3"
  - "dbus"
  - "dbus-x11"
  - "eterm"
  - "pixz"
