# Packages for examples/debian_snapshot.
#
#  Anytime this file is changed, the lockfile needs to be regenerated.
#
#  To generate the bookworm.lock.json run the following command
#
#     bazel run @bookworm//:lock
#
# See debian_package_index at WORKSPACE.bazel
version: 1
sources:
  - channel: bookworm main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240210T223313Z
  - channel: bookworm-security main
    url: https://snapshot-cloudflare.debian.org/archive/debian-security/20240210T223313Z
  - channel: bookworm-updates main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240210T223313Z/
archs:
  - "amd64"
  - "arm64"
packages:
  - "ncurses-base"
  - "libncurses6"
  - "tzdata"
  - "bash"
  - "coreutils" # for commands like `ls`
  # for apt list --installed
  - "dpkg"
  - "apt"
  - "perl"
  # test cacerts() compatibility
  - "ca-certificates"
  # virtual display/speaker
  - "grep"
  - "findutils"
  - "libstdc++6"
  - "dbus"
  - "dbus-x11"
  # xvfb
  - "xvfb"
  - "libxcb1"
  - "xauth"
  - "pulseaudio"
  # end xvfb
  - "chromium-driver"
  - "libfontconfig1"
  - "libfreetype6"
  - "xfonts-scalable"
  - "fonts-liberation"
  - "fonts-ipafont-gothic"
  - "sudo"
  - "python3"
