filegroup(
    name = "genai_config",
    srcs = [
        "genai_config.json",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "tokenizer_config",
    srcs = [
        "tokenizer.json",
        "tokenizer_config.json",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "tokenizer",
    srcs = [
        "embed_tokens.onnx",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "vision_encoder",
    srcs = [
        "vision_encoder_with_preprocessing.onnx",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "encoder",
    srcs = [
        "encoder_model.onnx",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "decoder",
    srcs = [
        "decoder_model_merged.onnx",
    ],
    visibility = ["//visibility:public"],
)
