name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GAR_LOCATION: ${{ vars.GAR_LOCATION }}
  APP: meeting-bot
  PROJECT_ID: ${{ vars.PROJECT_ID }}

jobs:
  deploy-meeting-bot:
    name: "Build and deploy the meeting bot"
    runs-on: ubuntu-22.04
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: "false"

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Mount bazel cache # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-${{ hashFiles('.bazelrc', '.bazelversion', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: |
            bazel-

      - name: "Build and push container"
        run: |
          sudo apt install -y yasm automake libtool m4
          bazel run //docker:push -- -r ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }} -t ${{ github.sha }}
