filegroup(
    name = "test_videos",
    srcs = glob([
        "*.mp4",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_images",
    srcs = glob([
        "*.png",
    ]),
    visibility = ["//visibility:public"],
)
